# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

TypeUser.create(name: 'superuser')
TypeUser.create(name: 'administrator')
TypeUser.create(name: 'supervisor')
TypeUser.create(name: 'client')
TypeUser.create(name: 'user')

Country.create(name: 'Antigua y Barbuda')
Country.create(name: 'Argentina')
Country.create(name: 'Bahamas')
Country.create(name: 'Barbados')
Country.create(name: 'Belice')
Country.create(name: 'Bolivia')
Country.create(name: 'Brasil')
Country.create(name: 'Canadá')
Country.create(name: 'Chile')
Country.create(name: 'Colombia')
Country.create(name: 'Costa Rica')
Country.create(name: 'Cuba')
Country.create(name: 'Dominica')
Country.create(name: 'Ecuador')
Country.create(name: 'El Salvador')
Country.create(name: 'Estados Unidos')
Country.create(name: 'Granada')
Country.create(name: 'Guatemala')
Country.create(name: 'Guyana')
Country.create(name: 'Haití')
Country.create(name: 'Honduras')
Country.create(name: 'Jamaica')
Country.create(name: 'México')
Country.create(name: 'Nicaragua')
Country.create(name: 'Panamá')
Country.create(name: 'Paraguay')
Country.create(name: 'Perú')
Country.create(name: 'República Dominicana')
Country.create(name: 'San Cristóbal y Nieves')
Country.create(name: 'San Vicente y las Granadinas')
Country.create(name: 'Santa Lucía')
Country.create(name: 'Surinam')
Country.create(name: 'Trinidad y Tobago')
Country.create(name: 'Uruguay')
Country.create(name: 'Venezuela')

Unit.create(name: 'g')
Unit.create(name: 'kg')
Unit.create(name: 'm')
Unit.create(name: 'km')
Unit.create(name: 'cm')
Unit.create(name: 'mm')
Unit.create(name: 'l')
Unit.create(name: 'cl')
Unit.create(name: 'ml')
Unit.create(name: 'c3')
Unit.create(name: 'm2')
Unit.create(name: 'm3')
Unit.create(name: 'cm2')
Unit.create(name: 'cm3')

Material.create(name: 'Aluminio')
Material.create(name: 'Cartón')
Material.create(name: 'Cobre')
Material.create(name: 'Papel')
Material.create(name: 'Plástico')
Material.create(name: 'Vidrio')